#! /bin/sh

source ~/.config/var_colors

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10
bspc config top_padding		28

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config -d '^9' window_gap 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox  ignore_ewmh_fullscreen={none} desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='^10' follow=off
bspc rule -a URxvt:float state=floating

bspc config presel_feedback_color $BLUE0
