#! /bin/sh

#if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
#	printf "%s\n" "The panel is already running." >&2
#	exit 1
#fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
#panel_wifi > "$PANEL_FIFO" &
#panel_battery > "$PANEL_FIFO" &
#clock -sf 'S%a %d/%m/%y %R' > "$PANEL_FIFO" &

conky -c ~/.config/panel/panel_conky > "$PANEL_FIFO" &

. ~/.config/panel/panel_colors

PANEL_FONT=-*-gohufont-medium-*-*-*-11-*-*-*-*-*-*-*
SYMBOL_FONT=-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1

panel_bar < "$PANEL_FIFO" | lemonbar -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -f "$SYMBOL_FONT" -F "$COLOR_DEFAULT_FG" -B "$BACKGROUND" | sh &
#panel_bar < "$PANEL_FIFO" | lemonbar -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -f "$SYMBOL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
