#! /bin/sh
#
# Example panel for lemonbar

. ~/.config/panel/panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
			;;

		L*)
			# wifi output
			wifi="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
			;;


		B*)
			# battery output
			bat="%{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
			;;

		T*)
			# xtitle output
			title="%{F$RED0}$(echo -e '\uE001')%{F$RED1}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:}${name}%{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$BLACK1
								BG=$BACKGROUND
								;;
							F*)
								# focused free desktop
								FG=$WHITE0
								BG=$BLACK1
								;;
							o*)
								# occupied desktop
								FG=$BLUE1
								BG=$BLACK0
								;;
							O*)
								# focused occupied desktop
								FG=$WHITE0
								BG=$BLACK1
								;;
							u*)
								# urgent desktop
								FG=$BLACK0
								BG=$RED0
								;;
							U*)
								# focused urgent desktop
								FG=$BLACK1
								BG=$MAGENTA1
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[LTG]*)
						# layout, state and flags
						wm="${wm}%{F$BLACK1}%{B$BACKGROUND}${name}%{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm}   ${title}%{r}${sys}"
done
