#! /bin/sh

sxhkd &
panel &
nitrogen --restore

bspc monitor -d 1 2 3 4 5 6 7 etc web games

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config -d web window_gap 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config presel_feedback_color "#A19EC7"


